---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull shahharsh8/speminiproject
      
    - name: running container
      shell: docker run -it -d shahharsh8/speminiproject
